### ISSUE TITLE
Create a partition on VHD disk

### ISSUE THREAD

**Issue by chiarelli** [jhermsmeier/node-vhd#6]
How do I create and mount a VHD disk partition, and can it operate as if it were a normal system file system?

**Comment by jhermsmeier** [comment]
Hey @chiarelli, VHDs only emulate block devices, to create partitions and file systems you'll need other modules to create a [Master Boot Record](https://en.wikipedia.org/wiki/Master_boot_record) (i.e. [`mbr`](https://github.com/jhermsmeier/node-mbr)) or [GUID Partition Table](https://en.wikipedia.org/wiki/GUID_Partition_Table) (i.e. [`gpt`](https://github.com/jhermsmeier/node-gpt)) and then file system drivers to format those partitions with the file system you want. Once you've got all that, you could hook your file system drivers up through [`fuse-bindings`](https://github.com/mafintosh/fuse-bindings) and then operate it as a normal file system in your OS, for example.

**NOTE** that this module currently doesn't have writes implemented properly – so using it to write to a VHD **will corrupt it** – there's a reason this is still in the 0.x version range. :)

**Comment by chiarelli** [comment]
I expressed myself poorly, in case I would like to know if you have how to create an MBR, create parturitions and mount to use within the node and not the operating system.
